# Generated by Django 2.1.5 on 2019-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtype', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
